// Treasury Tipped Occupation Codes (TTOC) — the complete list from the final
// "No Tax on Tips" regulations (26 CFR 1.224-1, Federal Register 2025-18278,
// Sept 22, 2025): 71 occupations in eight categories. Code 000 is for tips
// received from a non-qualifying occupation.
export const TTOC_CODES = [
  { code: '000', title: 'Non-qualifying occupation', category: 'General' },
  // 100s — Beverage and Food Service
  { code: '101', title: 'Bartenders', category: 'Beverage and Food Service' },
  { code: '102', title: 'Wait Staff', category: 'Beverage and Food Service' },
  { code: '103', title: 'Food or Beverage Servers, Non-restaurant', category: 'Beverage and Food Service' },
  { code: '104', title: 'Dining Room and Cafeteria Attendants and Bartender Helpers', category: 'Beverage and Food Service' },
  { code: '105', title: 'Chefs and Cooks', category: 'Beverage and Food Service' },
  { code: '106', title: 'Food Preparation Workers', category: 'Beverage and Food Service' },
  { code: '107', title: 'Fast Food and Counter Workers', category: 'Beverage and Food Service' },
  { code: '108', title: 'Dishwashers', category: 'Beverage and Food Service' },
  { code: '109', title: 'Host Staff, Restaurant, Lounge, and Coffee Shop', category: 'Beverage and Food Service' },
  { code: '110', title: 'Bakers', category: 'Beverage and Food Service' },
  // 200s — Entertainment and Events
  { code: '201', title: 'Gambling Dealers', category: 'Entertainment and Events' },
  { code: '202', title: 'Gambling Change Persons and Booth Cashiers', category: 'Entertainment and Events' },
  { code: '203', title: 'Gambling Cage Workers', category: 'Entertainment and Events' },
  { code: '204', title: 'Gambling and Sports Book Writers and Runners', category: 'Entertainment and Events' },
  { code: '205', title: 'Dancers', category: 'Entertainment and Events' },
  { code: '206', title: 'Musicians and Singers', category: 'Entertainment and Events' },
  { code: '207', title: 'Disc Jockeys, Except Radio', category: 'Entertainment and Events' },
  { code: '208', title: 'Entertainers and Performers', category: 'Entertainment and Events' },
  { code: '209', title: 'Digital Content Creators', category: 'Entertainment and Events' },
  { code: '210', title: 'Ushers, Lobby Attendants, and Ticket Takers', category: 'Entertainment and Events' },
  { code: '211', title: 'Locker Room, Coatroom, and Dressing Room Attendants', category: 'Entertainment and Events' },
  // 300s — Hospitality and Guest Services
  { code: '301', title: 'Baggage Porters and Bellhops', category: 'Hospitality and Guest Services' },
  { code: '302', title: 'Concierges', category: 'Hospitality and Guest Services' },
  { code: '303', title: 'Hotel, Motel, and Resort Desk Clerks', category: 'Hospitality and Guest Services' },
  { code: '304', title: 'Maids and Housekeeping Cleaners', category: 'Hospitality and Guest Services' },
  // 400s — Home Services
  { code: '401', title: 'Home Maintenance and Repair Workers', category: 'Home Services' },
  { code: '402', title: 'Home Landscaping and Groundskeeping Workers', category: 'Home Services' },
  { code: '403', title: 'Home Electricians', category: 'Home Services' },
  { code: '404', title: 'Home Plumbers', category: 'Home Services' },
  { code: '405', title: 'Home Heating and Air Conditioning Mechanics and Installers', category: 'Home Services' },
  { code: '406', title: 'Home Appliance Installers and Repairers', category: 'Home Services' },
  { code: '407', title: 'Home Cleaning Service Workers', category: 'Home Services' },
  { code: '408', title: 'Locksmiths', category: 'Home Services' },
  { code: '409', title: 'Roadside Assistance Workers', category: 'Home Services' },
  // 500s — Personal Services
  { code: '501', title: 'Personal Care and Service Workers', category: 'Personal Services' },
  { code: '502', title: 'Private Event Planners', category: 'Personal Services' },
  { code: '503', title: 'Private Event and Portrait Photographers', category: 'Personal Services' },
  { code: '504', title: 'Private Event Videographers', category: 'Personal Services' },
  { code: '505', title: 'Event Officiants', category: 'Personal Services' },
  { code: '506', title: 'Pet and Show Animal Caretakers', category: 'Personal Services' },
  { code: '507', title: 'Tutors', category: 'Personal Services' },
  { code: '508', title: 'Nannies and Babysitters', category: 'Personal Services' },
  { code: '509', title: 'Visual Artists', category: 'Personal Services' },
  { code: '510', title: 'Floral Designers', category: 'Personal Services' },
  // 600s — Personal Appearance and Wellness
  { code: '601', title: 'Skincare Specialists', category: 'Personal Appearance and Wellness' },
  { code: '602', title: 'Massage Therapists', category: 'Personal Appearance and Wellness' },
  { code: '603', title: 'Barbers, Hairdressers, Hairstylists, and Cosmetologists', category: 'Personal Appearance and Wellness' },
  { code: '604', title: 'Shampooers', category: 'Personal Appearance and Wellness' },
  { code: '605', title: 'Manicurists and Pedicurists', category: 'Personal Appearance and Wellness' },
  { code: '606', title: 'Eyebrow and Eyelash Technicians', category: 'Personal Appearance and Wellness' },
  { code: '607', title: 'Makeup Artists', category: 'Personal Appearance and Wellness' },
  { code: '608', title: 'Exercise Trainers and Group Fitness Instructors', category: 'Personal Appearance and Wellness' },
  { code: '609', title: 'Tattoo Artists and Piercers', category: 'Personal Appearance and Wellness' },
  { code: '610', title: 'Tailors', category: 'Personal Appearance and Wellness' },
  { code: '611', title: 'Shoe and Leather Workers and Repairers', category: 'Personal Appearance and Wellness' },
  // 700s — Recreation and Instruction
  { code: '701', title: 'Golf Caddies', category: 'Recreation and Instruction' },
  { code: '702', title: 'Self-Enrichment Teachers', category: 'Recreation and Instruction' },
  { code: '703', title: 'Recreational and Tour Pilots', category: 'Recreation and Instruction' },
  { code: '704', title: 'Tour Guides', category: 'Recreation and Instruction' },
  { code: '705', title: 'Travel Guides', category: 'Recreation and Instruction' },
  { code: '706', title: 'Sports and Recreation Instructors', category: 'Recreation and Instruction' },
  // 800s — Transportation and Delivery
  { code: '801', title: 'Parking and Valet Attendants', category: 'Transportation and Delivery' },
  { code: '802', title: 'Taxi and Rideshare Drivers and Chauffeurs', category: 'Transportation and Delivery' },
  { code: '803', title: 'Shuttle Drivers', category: 'Transportation and Delivery' },
  { code: '804', title: 'Goods Delivery People', category: 'Transportation and Delivery' },
  { code: '805', title: 'Personal Vehicle and Equipment Cleaners', category: 'Transportation and Delivery' },
  { code: '806', title: 'Private and Charter Bus Drivers', category: 'Transportation and Delivery' },
  { code: '807', title: 'Water Taxi Operators and Charter Boat Workers', category: 'Transportation and Delivery' },
  { code: '808', title: 'Rickshaw, Pedicab, and Carriage Drivers', category: 'Transportation and Delivery' },
  { code: '809', title: 'Home Movers', category: 'Transportation and Delivery' },
  { code: '810', title: 'Gas Pump Attendant', category: 'Transportation and Delivery' },
];

export const TTOC_OPTIONS = TTOC_CODES.map(c => ({ value: c.code, label: `${c.code} — ${c.title}` }));
